
create table if not exists users (
    id bigint  generated by default as identity,
    username   varchar(255) unique not null,
    email      varchar(255) unique not null,
    password   varchar(255) not null default '',
    full_name  varchar(255) not null default '',
    phone      varchar(255) not null default '',
    created_at timestamptz  not null default now(),
    updated_at timestamptz  not null default now()
);

alter table users add constraint users_pk primary key (id);


create table if not exists scenarios (
    id bigint    generated by default as identity,
    name         varchar(255) not null default '',
    category     varchar(255) not null default '',
    description  text         not null default '',
    keywords     text[]       not null default '{}',
    instructions text         not null default '',
    created_at   timestamptz  not null default now(),
    updated_at   timestamptz  not null default now()
);


INSERT INTO users (username, email, password, full_name, phone) VALUES
('john_doe', 'john_doe@example.com', 'password123', 'John Doe', '+1234567890'),
('jane_doe', 'jane_doe@example.com', 'password456', 'Jane Doe', '+2345678901'),
('bob_smith', 'bob_smith@example.com', 'password789', 'Bob Smith', '+3456789012'),
('mary_jones', 'mary_jones@example.com', 'password321', 'Mary Jones', '+4567890123'),
('mike_johnson', 'mike_johnson@example.com', 'password654', 'Mike Johnson', '+5678901234'),
('susan_wilson', 'susan_wilson@example.com', 'password987', 'Susan Wilson', '+6789012345'),
('david_lee', 'david_lee@example.com', 'passwordabc', 'David Lee', '+7890123456'),
('lisa_wang', 'lisa_wang@example.com', 'passworddef', 'Lisa Wang', '+8901234567'),
('steve_lee', 'steve_lee@example.com', 'passwordghi', 'Steve Lee', '+9012345678'),
('emily_chen', 'emily_chen@example.com', 'passwordjkl', 'Emily Chen', '+0123456789'),
('adam_kim', 'adam_kim@example.com', 'passwordmno', 'Adam Kim', '+1234567890'),
('jennifer_lee', 'jennifer_lee@example.com', 'passwordpqr', 'Jennifer Lee', '+2345678901'),
('brian_harris', 'brian_harris@example.com', 'passwordstu', 'Brian Harris', '+3456789012'),
('amy_johnson', 'amy_johnson@example.com', 'passwordvwx', 'Amy Johnson', '+4567890123'),
('mark_smith', 'mark_smith@example.com', 'passwordyz1', 'Mark Smith', '+5678901234'),
('kelly_wilson', 'kelly_wilson@example.com', 'password234', 'Kelly Wilson', '+6789012345');

INSERT INTO scenarios (name, category, description, keywords, instructions) VALUES
('Allergic Reaction', 'Allergies', 'A severe reaction to an allergen, such as a food or insect bite.', '{allergies, reaction}', '1. Call for emergency medical help\n2. Administer epinephrine if available\n3. Monitor breathing and provide CPR if necessary.'),
('Broken Arm', 'Physical Injuries', 'A fracture in one of the bones in the arm, often caused by trauma.', '{injury, arm, fracture}', '1. Call for emergency medical help\n2. Immobilize the arm with a splint or sling\n3. Apply ice to reduce swelling\n4. Administer pain medication as needed.'),
('Heart Attack', 'Cardiac Emergencies', 'A blockage in the arteries that supply blood to the heart, leading to damage or death of heart muscle tissue.', '{heart, attack, emergency}', '1. Call for emergency medical help\n2. Have the person chew and swallow an aspirin if not allergic\n3. Administer CPR if necessary\n4. Use an automated external defibrillator (AED) if available.'),
('Asthma Attack', 'Respiratory Emergencies', 'A sudden onset of wheezing, shortness of breath, and chest tightness, often caused by exposure to allergens or irritants.', '{asthma, attack, emergency}', '1. Have the person sit upright and stay calm\n2. Administer a rescue inhaler if available\n3. Call for emergency medical help if the inhaler does not work\n4. Administer oxygen if available.'),
('Heat Exhaustion', 'Environmental Emergencies', 'A condition caused by prolonged exposure to high temperatures, often resulting in dehydration and electrolyte imbalances.', '{heat, exhaustion, dehydration}', '1. Move the person to a cool, shaded area\n2. Offer water or sports drinks to rehydrate\n3. Apply cool, wet towels to the skin\n4. Monitor for signs of heat stroke.'),
('Sprained Ankle', 'Physical Injuries', 'An injury to the ligaments in the ankle, often caused by a sudden twist or turn.', '{injury, ankle, sprain}', '1. Rest the affected ankle\n2. Elevate the ankle above heart level\n3. Apply ice to reduce swelling\n4. Compress the ankle with a bandage\n5. Administer pain medication as needed.'),
('Stroke', 'Neurological Emergencies', 'A blockage or rupture of blood vessels in the brain, leading to loss of brain function and potentially life-threatening complications.', '{stroke, emergency}', '1. Call for emergency medical help\n2. Note the time the symptoms started\n3. Administer aspirin if not allergic\n4. Monitor breathing and provide CPR if necessary\n5. Keep the person calm and comfortable.'),
('Poisoning', 'Toxicological Emergencies', 'Exposure to a harmful substance, such as a chemical or medication, leading to potentially life-threatening symptoms.', '{poisoning, emergency}', '1. Call for emergency medical help\n2. Identify the substance and amount ingested\n3. Administer activated charcoal if available\n4. Monitor breathing and provide CPR if necessary\n5. Keep the person calm and comfortable.');