
create table if not exists users (
    id bigint  generated by default as identity,
    username   varchar(255) unique not null,
    email      varchar(255) unique not null,
    password   varchar(255) not null default '',
    full_name  varchar(255) not null default '',
    phone      varchar(255) not null default '',
    created_at timestamptz  not null default now(),
    updated_at timestamptz  not null default now()
);

alter table users add constraint users_pk primary key (id);


create table if not exists scenarios (
    id bigint    generated by default as identity,
    name         varchar(255) not null default '',
    category     varchar(255) not null default '',
    description  text         not null default '',
    keywords     text[]       not null default '{}',
    instructions text         not null default '',
    created_at   timestamptz  not null default now(),
    updated_at   timestamptz  not null default now()
);


INSERT INTO users (username, email, password, full_name, phone) 
VALUES ('john_doe', 'john_doe@example.com', 'password123', 'John Doe', '+1234567890');

INSERT INTO users (username, email, password, full_name, phone) 
VALUES ('jane_doe', 'jane_doe@example.com', 'password456', 'Jane Doe', '+2345678901');

INSERT INTO users (username, email, password, full_name, phone) 
VALUES ('bob_smith', 'bob_smith@example.com', 'password789', 'Bob Smith', '+3456789012');

INSERT INTO users (username, email, password, full_name, phone) 
VALUES ('mary_jones', 'mary_jones@example.com', 'password321', 'Mary Jones', '+4567890123');

INSERT INTO users (username, email, password, full_name, phone) 
VALUES ('mike_johnson', 'mike_johnson@example.com', 'password654', 'Mike Johnson', '+5678901234');

INSERT INTO users (username, email, password, full_name, phone) 
VALUES ('susan_wilson', 'susan_wilson@example.com', 'password987', 'Susan Wilson', '+6789012345');

INSERT INTO users (username, email, password, full_name, phone) 
VALUES ('david_lee', 'david_lee@example.com', 'passwordabc', 'David Lee', '+7890123456');

INSERT INTO users (username, email, password, full_name, phone) 
VALUES ('lisa_wang', 'lisa_wang@example.com', 'passworddef', 'Lisa Wang', '+8901234567');

INSERT INTO users (username, email, password, full_name, phone) 
VALUES ('steve_lee', 'steve_lee@example.com', 'passwordghi', 'Steve Lee', '+9012345678');

INSERT INTO users (username, email, password, full_name, phone) 
VALUES ('emily_chen', 'emily_chen@example.com', 'passwordjkl', 'Emily Chen', '+0123456789');

INSERT INTO users (username, email, password, full_name, phone) 
VALUES ('adam_kim', 'adam_kim@example.com', 'passwordmno', 'Adam Kim', '+1234567890');

INSERT INTO users (username, email, password, full_name, phone) 
VALUES ('jennifer_lee', 'jennifer_lee@example.com', 'passwordpqr', 'Jennifer Lee', '+2345678901');

INSERT INTO users (username, email, password, full_name, phone) 
VALUES ('brian_harris', 'brian_harris@example.com', 'passwordstu', 'Brian Harris', '+3456789012');

INSERT INTO users (username, email, password, full_name, phone) 
VALUES ('amy_johnson', 'amy_johnson@example.com', 'passwordvwx', 'Amy Johnson', '+4567890123');

INSERT INTO users (username, email, password, full_name, phone) 
VALUES ('mark_smith', 'mark_smith@example.com', 'passwordyz1', 'Mark Smith', '+5678901234');

INSERT INTO users (username, email, password, full_name, phone) 
VALUES ('kelly_wilson', 'kelly_wilson@example.com', 'password234', 'Kelly Wilson', '+6789012345');
