
create table if not exists users 
{
    id bigint  generated by default as identity,
    username   varchar(255) unique not null
    password   varchar(255) unique not null
    full_name  varchar(255) not null default '',
    email      varchar(255) not null default '',
    phone      varchar(255) not null default '',
    password   varchar(255) not null default '',
    created_at timestamp    not null default now(),
    updated_at timestamp    not null default now()
}

alter table users add constraint users_pk primary key (id);